export const SELECT_MATERIAL = "SELECT_MATERIAL";
export const GET_SELECT_PROJECT = 'GET_SELECT_PROJECT';
export const START_LOADING = 'START_LOADING';
export const SELECT_MATERIAL_ERROR = 'SELECT_MATERIAL_ERROR';