export const SELECT_MATERIAL = "SELECT_MATERIAL";
export const GET_SELECT_PROJECT = 'GET_SELECT_PROJECT';
export const SELECT_START_LOAD = 'SELECT_START_LOAD';
export const SELECT_MATERIAL_ERROR = 'SELECT_MATERIAL_ERROR';